### PR TITLE
add is_shader and is_texture commands

### PR DESCRIPTION
**Pull request by ddefisher**
For `Implement isShader`and `Implement isTexture` in https://github.com/servo/servo/issues/10209#issuecomment-217279125

### CODE REVIEW

**Comment by autrilla** [comment]
I think this broke my build:

```
 expected `()`,
    found `u8`
(expected (),
    found u8) [E0308]
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:269         match self {
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:270             WebGLCommand::GetContextAttributes(sender) =>
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:271                 sender.send(*ctx.borrow_attributes()).unwrap(),
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:272             WebGLCommand::ActiveTexture(target) =>
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:273                 gl::active_texture(target),
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:274             WebGLCommand::AttachShader(program_id, shader_id) =>
                                                                                                        ...
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:269:9: 474:10 help: run `rustc --explain E0308` to see a detailed explanation
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:331:17: 331:38 note: match arm with an incompatible type
/home/autrilla/src/servo/.cargo/git/checkouts/webrender_traits-e24a580db67dabe6/master/src/webgl.rs:331                 gl::is_shader(shader),
```

**Comment by ddefisher** [comment]
looking at this now.  I am not sure why I was able to build it.  Trying to fix it quick.

**Comment by emilio** [comment]
Just quick FYI for all the participants and for keeping record of this, this PR was backed out in #53, since the build failed with it.

It was not caught by our CI because #42 took rid of `cargo build`, but that's already fixed in #52 .

**Pull request merged**
