### PR TITLE
Read pixels

### PR DESCRIPTION
**Pull request by dzbarsky**

### CODE REVIEW

**Comment by dzbarsky** [comment]
@emilio ^ (it has some other gunk in there because I couldn't work of master until the build is fixed)
Does this look sane? With this PR and the servo one ReadPixels returns incorrect results, but I haven't had a chance to figure out whether the bug is in the uniforms and such or ReadPixels itself (more likely I'd imagine)

**Comment by emilio** [comment]
Yes, it looks sane, what kind of incorrect results do you see?

If it's in the tests, most likely it's because they use some WebGL-specific pixelStorei values, some of which we currently don't use.

**Comment by dzbarsky** [comment]
Unexpected subtest result in /webgl/conformance-1.0.3/conformance/programs/gl-bind-attrib-location-long-names-test.html:
  │ FAIL [expected PASS] WebGL test #4: at (0, 0) expected: 0,255,0,255 was 255,255,255,255
  │   → assert_true: at (0, 0) expected: 0,255,0,255 was 255,255,255,255 expected true got false

**Comment by emilio** [comment]
@dzbarsky: Does it happen consistently? Looking at that test, they seem to clear the canvas to black (that's ok, 255, 255, 255, 255), and later draw over it using attributes, so that might be a bug, but I'm tempted to say it's almost surely due to the attributes and not due to readPixels.

**Comment by emilio** [comment]
Also, it might be some message ordering issue (like, we send the drawArrays and readPixels messages and they arrive in the wrong order, but that's even less likely)

**Comment by dzbarsky** [comment]
@emilio ok, if you think ReadPixels isn't to blame let's land is :)

**Comment by emilio** [comment]
@dzbarsky: Happy to do that, but you'll have to fix the merge conflict first though :P

**Comment by dzbarsky** [comment]
@emilio ping, rebased

**Pull request merged**
