### PR TITLE
Added build back to travis (fixes #51)

### LINKED ISSUE #51: CI should at least try to compile the project
Currently CI only runs a tidiness check, which has caused servo builds to break when people updated their wr_traits dependency to the newest version. I suggest we at least make travis build the project, and considering there's some nontrivial glue code in this project, it may be worth it to run tests on CI also.

Thoughts?

### PR DESCRIPTION
**Pull request by autrilla**

### CODE REVIEW

**Comment by autrilla** [comment]
It looks like the compilation is failing. It fails for me locally too:

```
[autrilla:~/src/webrender_traits] master(5) ± cargo build 
 Downloading serde v0.7.4
 Downloading offscreen_gl_context v0.1.4
 Downloading gleam v0.2.18
 Downloading serde_macros v0.7.4
 Downloading app_units v0.2.4
 Downloading xml-rs v0.3.2
 Downloading bitflags v0.6.0
 Downloading serde_codegen v0.7.4
 Downloading quasi_macros v0.10.0
 Downloading quasi v0.10.0
 Downloading aster v0.16.0
 Downloading quasi_codegen v0.10.0
 Downloading lazy_static v0.2.1
   Compiling bitflags v0.6.0
   Compiling serde v0.7.4
   Compiling lazy_static v0.2.1
   Compiling serde_codegen v0.7.4
   Compiling xml-rs v0.3.2
   Compiling quasi v0.10.0
   Compiling aster v0.16.0
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.10.0/src/lib.rs:82:46: 82:65 error: this function takes 2 parameters but 1 parameter was supplied [E0061]
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.10.0/src/lib.rs:82         vec![ast::TokenTree::Token(DUMMY_SP, token::Ident(*self))]
                                                                                                                                       ^~~~~~~~~~~~~~~~~~~
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.10.0/src/lib.rs:82:9: 82:67 note: in this expansion of vec! (defined in <std macros>)
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi-0.10.0/src/lib.rs:82:46: 82:65 help: run `rustc --explain E0061` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/aster-0.16.0/src/item.rs:114:30: 114:47 error: unresolved name `keywords::Invalid` [E0425]
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/aster-0.16.0/src/item.rs:114         self.build_item_kind(keywords::Invalid.ident(), item)
                                                                                                                         ^~~~~~~~~~~~~~~~~
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/aster-0.16.0/src/item.rs:114:30: 114:47 help: run `rustc --explain E0425` to see a detailed explanation
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/aster-0.16.0/src/item.rs:1183:38: 1183:55 error: unresolved name `keywords::Invalid` [E0425]
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/aster-0.16.0/src/item.rs:1183         self.builder.build_item_kind(keywords::Invalid.ident(), ty_)
                                                                                                                                  ^~~~~~~~~~~~~~~~~
/home/autrilla/.cargo/registry/src/github.com-88ac128001ac3a9a/aster-0.16.0/src/item.rs:1183:38: 1183:55 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 2 previous errors
error: Could not compile `quasi`.

```

**Comment by ddefisher** [comment]
One of the reasons the travis CI build is failing is because of my error in this pr #49 , #50 should fix it.

**Comment by emilio** [comment]
Yes, actually the build failds because of #49, but the breakage you're seeing is because of `quasi` and `aster`, that are crates that depend on `libsyntax` that ultimately depends on the compiler you're using.

So either using the latest nighlty or running `cargo update -p aster --precise xxx` and `cargo update -p quasi --precise xxx`, where xxx are versions compatible with your current rustc versions should fix it.

I'm in favour of adding this back to the travis config though (it seems it was removed accidentally when adding tidy in #42), but will have to wait until #50 is fixed and landed.

**Comment by emilio** [comment]
I reverted the changes in #49 in #53, so this should be mergeable again (modulo maybe aster and quasi breackage?).

@bors-servo: r+

**Comment by emilio** [comment]
@bors-servo: r+

Thanks for catching this @autrilla! :-)

**Pull request merged**
